### ISSUE TITLE
How do I use AsyncChatbot Official?

### ISSUE THREAD

**Issue by The-Ballen** [acheong08/ChatGPT#545]
I've tried doing

```
from revChatGPT.Official import AsyncChatbot as Chatbot

chatbot = Chatbot(api_key=openai_api)

async with ctx.typing():
                        response = await chatbot.ask(prompt)
                        await ctx.message.reply(response["choices"][0]["text"])
```

but that's the output:

```
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages
\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "index.py", line 96, in on_message
    response = await chatbot.ask(prompt)
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages
\revChatGPT\Official.py", line 206, in ask
    return self._process_completion(user_request, completion)
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages
\revChatGPT\Official.py", line 59, in _process_completion
    if completion.get("choices") is None:
AttributeError: 'coroutine' object has no attribute 'get'
C:\Users\me\AppData\Local\Programs\Python\Python38\lib\site-packages\discord
\client.py:416: RuntimeWarning: coroutine 'Completion.acreate' was never awaited
```

So how should I use AsyncChatbot?

**Comment by The-Ballen** [comment]
nevermind, I just used 'Sync to Async' and it solved my problem.

**Comment by acheong08** [comment]
Valid issue

**Comment by slippersheepig** [comment]
My telegram bot works fine with 1.1.2 release, but the fix for [#537](https://github.com/acheong08/ChatGPT/issues/537#issue-1569837375) and the 1.1.3 release broken [sendChatAction](https://core.telegram.org/bots/api#sendchataction) function of telegram, the error is as mentioned above. Hope to bump new version soon. Thanks.

**Comment by acheong08** [comment]
`git clone https://github.com/acheong08/ChatGPT` and `cd ChatGPT` and `pip3 install .` to get the latest commit to test. I haven't tried out the fix yet

**Comment by slippersheepig** [comment]
Just test it, still the same error, maybe my coding problem.

**Comment by acheong08** [comment]
Probably something on my part. I have never worked with async in Python before. Look around the source code and see what my mistake is if you may

**Comment by acheong08** [comment]
Fixed https://github.com/acheong08/ChatGPT/releases/tag/1.1.4
