### ISSUE TITLE
[BUG] Error... Logging in again 「An error will be reported when the proxy parameter is added」

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#671]
<img width="997" alt="image" src="https://user-images.githubusercontent.com/19570026/218319289-c19817e6-e654-4653-8f92-6d4e320efedb.png">

**Comment by acheong08** [comment]
can you debug by printing error code?

**Comment by acheong08** [comment]
status code

**Comment by jevenzh** [comment]
I have the same error using the latest version.

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/218320004-b7c5f53d-1445-4c5f-b5a0-3fec0f798a5d.png)

**Comment by jevenzh** [comment]
thanks! mine was resolved after adding the proxy.

**Comment by antongolubev5** [comment]
@jevenzh  what should i send to parameter proxy? thank you

chatbot = Chatbot(email="npublic2016@yandex.ru", password="chatgptservice23", ### proxy="")

**Comment by acheong08** [comment]
`socks5://IP:PORT`

**Comment by acheong08** [comment]
`--insecure-auth` auto selects a proxy

**Comment by antongolubev5** [comment]
@acheong08  V2.py: error: unrecognized arguments: --insecure-auth

**Comment by antongolubev5** [comment]
@acheong08 

PS C:\Users\anton\PycharmProjects\Targeted-SA-Application> python -m revChatGPT.V2 -e "" -p "" --insecure-auth 

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT

Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.


You:
hello how are u

ChatGPT:
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\V2.py", line 325, in <module>
    asyncio.run(main())
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\V2.py", line 315, in main
    result = line["choices"][0]["text"].replace("<|im_end|>", "")



TypeError: string indices must be integers

**Comment by acheong08** [comment]
Can you print the full line?

**Comment by acheong08** [comment]
Also try upgrading: `pip3 install --upgrade revChatGPT`

**Comment by antongolubev5** [comment]
@acheong08 after updating to  revChatGPT-2.1.11 i have a new error:

ChatGPT:
error: OpenAI error!
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\V2.py", line 334, in <module>
    asyncio.run(main())
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\V2.py", line 323, in main
    async for line in chatbot.ask(prompt=prompt):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\V2.py", line 164, in ask
    raise Exception("OpenAI error!")
Exception: OpenAI error!
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001D373CDA520>
transport: <_ProactorSocketTransport fd=1472 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000001D34CEA3CA0>
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

**Comment by Jun-jie-Huang** [comment]
> @acheong08 after updating to revChatGPT-2.1.11 i have a new error:
> 
> ChatGPT: error: OpenAI error! Traceback (most recent call last): File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\V2.py", line 334, in asyncio.run(main()) File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete return future.result() File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\V2.py", line 323, in main async for line in chatbot.ask(prompt=prompt): File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\V2.py", line 164, in ask raise Exception("OpenAI error!") Exception: OpenAI error! Fatal error on SSL transport protocol: <asyncio.sslproto.SSLProtocol object at 0x000001D373CDA520> transport: <_ProactorSocketTransport fd=1472 read=<_OverlappedFuture cancelled>> Traceback (most recent call last): File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog self._transport.write(chunk) File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write self._loop_writing(data=bytes(data)) File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing self._write_fut = self._loop._proactor.send(self._sock, data) AttributeError: 'NoneType' object has no attribute 'send' Exception ignored in: <function _SSLProtocolTransport.**del** at 0x000001D34CEA3CA0> Traceback (most recent call last): File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 321, in **del** File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 316, in close File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed RuntimeError: Event loop is closed

Have the same error after upgrading to 2.1.13. But will have the same error as in [this issue](https://github.com/acheong08/ChatGPT/issues/693) if using 2.1.11
